'use client';
import Records from '@/components/Records';
import { useRef, useState } from 'react';
import AlternateLayouts from '@/components/AlternateLayouts';
import Updates from '@/components/Updates';
import { Bell, Search, ChevronDown, ChevronRight, Phone, FileText, CalendarDays, Mail, Link as LinkIcon, Pill, UserRound, Settings, ShieldCheck, CircleDollarSign, X, Menu, CheckCircle2, Upload, ExternalLink } from 'lucide-react';
import { veteran, claim, appointment, messages } from '@/lib/mock-data';
const services = ['Refill prescriptions', 'View VA letters', 'Manage appointments', 'Track claims'];
const serviceIcons = [Pill, FileText, CalendarDays, FileText];
export default function Home() {
 const [travelSubmitted, setTravelSubmitted] = useState(false);
 const [layout, setLayout] = useState(1);
 const dialog = useRef<HTMLDialogElement>(null);
 const [panel, setPanel] = useState(''); const [query, setQuery] = useState(''); const [mobile, setMobile] = useState(false); const [file, setFile] = useState(''); const [uploaded, setUploaded] = useState(false); const [read, setRead] = useState(false);
 function open(title: string) { setPanel(title); dialog.current?.showModal(); if(title === 'Your messages') setRead(true); }
 const action = (label: string, title = label) => <button className="text-link" onClick={() => open(title)}>{label}<ChevronRight size={18}/></button>;
 return <div className={`layout-version layout-version-${layout}`}>
 <a className="skip-link" href="#main">Skip to main content</a>

 <header className="header"><div className="header-inner"><a className="brand" href={`${process.env.NEXT_PUBLIC_BASE_PATH || ''}/`} aria-label="My VA home"><strong>VA</strong><span>U.S. Department of<br/>Veterans Affairs</span></a><nav className={mobile ? 'navigation expanded' : 'navigation'} aria-label="Main navigation"><button onClick={() => open('VA.gov home')}>VA.gov home</button>{['Health care','Benefits','Life events','Resources','Support'].map(item => <button key={item} onClick={() => open(item)}>{item}<ChevronDown size={13}/></button>)}</nav><div className="header-tools"><form className="search" onSubmit={e => {e.preventDefault();open('Search VA.gov');}} role="search"><button aria-label="Search"><Search size={19}/></button><input aria-label="Search VA.gov" placeholder="Search VA.gov" value={query} onChange={e=>setQuery(e.target.value)}/></form><button className="notification" aria-label={read ? 'No unread messages' : '2 unread messages'} onClick={()=>open('Your messages')}><Bell size={23}/>{!read && <span/>}</button><button className="account" onClick={()=>open('Your profile')}><span className="avatar small">AM</span><span>Alex</span><ChevronDown size={14}/></button><button className="mobile-toggle" aria-label="Toggle navigation" aria-expanded={mobile} onClick={()=>setMobile(!mobile)}><Menu/></button></div></div></header>
 <div className="prototype"><div className="layout-picker" role="group" aria-label="Choose homepage layout">{[1,2,3].map(n=><button key={n} aria-pressed={layout===n} aria-label={`Layout ${n}: ${['Refined VA','Action first','Personal overview'][n-1]}`} onClick={()=>{setLayout(n);setMobile(false)}}>{n}</button>)}</div><span className="layout-name">{['Refined VA','Action first','Personal overview'][layout-1]}</span><span className="prototype-dot"/> DESIGN PREVIEW <span className="prototype-note">Fictional sample data · Not an official VA website</span></div>
 <div className="crisis-bar"><div><a href="https://www.veteranscrisisline.net/" target="_blank" rel="noreferrer"><Phone size={15}/>Veterans Crisis Line: 988 then press 1<ExternalLink size={12}/></a></div></div>
 {layout === 1 ? <main id="main" className="page"><div className="breadcrumb">My VA</div><div className="dashboard"><div className="main-column"><div className="welcome-profile-row"><section className="welcome"><p className="eyebrow">YOUR PERSONAL VA HOME</p><h1>Welcome back, Alex</h1><p>Here’s what’s happening with your VA benefits, health care, and more.</p></section>
<section className="side-card profile-card"><div className="service-banner"><img src={`${process.env.NEXT_PUBLIC_BASE_PATH || ''}/marine-corps-emblem.png`} alt="United States Marine Corps emblem" width="56" height="56"/><span>UNITED STATES<br/><strong>MARINE CORPS</strong></span></div><div className="profile"><span className="avatar">AM</span><div><h2>{veteran.name}</h2><p>{veteran.service}</p><p className="service-years">{veteran.serviceYears}</p></div></div><div className="profile-links">{[[UserRound,'View and edit your profile','Your profile'],[Settings,'Account settings','Account settings'],[ShieldCheck,'Security and sign-in','Security and sign-in']].map(([Icon,label,title]) => {const I=Icon as typeof UserRound;return <button key={String(label)} onClick={()=>open(String(title))}><I size={21}/><span>{String(label)}</span><ChevronRight size={17}/></button>})}</div></section></div>
 <Updates open={open} uploaded={uploaded} file={file} travelSubmitted={travelSubmitted}/>
 <div className="activity"><section><div className="section-heading"><h2>Your claims and appeals</h2><span>1 active claim</span></div><div className="activity-body"><FileText className="section-icon" size={35}/><div className="activity-content"><div className="row-title"><h3>{claim.title}</h3>{action('View claim details','Claim details')}</div><p className="metadata">Claim received {claim.received}<span className="divider">|</span>Claim number: {claim.number}</p><span className="status">Step {claim.step} of {claim.totalSteps} — {claim.status}</span><p className="jurisdiction">Temporary jurisdiction: <strong>{claim.temporaryJurisdiction}</strong></p><p className="description">We’re reviewing your evidence. We’ll let you know if we need anything else.</p></div></div></section>
 <section><div className="section-heading"><h2>Your health care</h2></div><div className="activity-body"><CalendarDays className="section-icon" size={35}/><div className="activity-content"><div className="row-title"><span className="subheading">Next appointment</span>{action('View appointment details','Appointment details')}</div><h3 className="date">{appointment.date}</h3><div className="appointment-bottom"><div><strong>{appointment.type}</strong><p>{appointment.time}</p><p className="metadata">{appointment.location}</p></div><button className="secondary" onClick={()=>open('Manage appointments')}>Manage appointments</button></div></div></div></section>
 <section><div className="section-heading"><h2>Your messages</h2>{read && <span>All caught up</span>}</div><div className="activity-body"><Mail className="section-icon" size={35}/><div className="activity-content"><div className="row-title"><h3>{read ? 'Your messages' : '2 unread messages'}</h3>{action('Go to messages','Your messages')}</div><p className="description">{read ? 'You’ve read your latest messages from VA.' : 'You have new messages from your VA care team and benefits team.'}</p></div></div></section></div>
 <div className="help-strip"><ShieldCheck size={19}/><p>Your information, all in one place.<span> Keep your contact details up to date so we can stay in touch.</span></p><button onClick={()=>open('Your profile')}>Review your profile</button></div></div>
 <aside aria-label="Your profile and quick links">
 <section className="side-card quick-card"><h2><LinkIcon size={26}/>Quick links</h2><div className="quick-links">{services.map((name,i)=>{const Icon=serviceIcons[i];return <button key={name} onClick={()=>open(name)}><Icon size={27}/><span>{name}</span><ChevronRight size={18}/></button>})}</div></section>
 <section className="side-card benefits"><h2><CircleDollarSign size={28}/>Your benefits and payments</h2><div className="benefit-row"><div><p>Disability rating</p><strong>{veteran.disabilityRating}</strong></div>{action('View your benefits','Your benefits')}</div><div className="benefit-row"><div><p>Last payment</p><strong>{veteran.lastPayment}</strong><p className="payment-date">{veteran.paymentDate}</p></div>{action('View payment history','Payment history')}</div></section><p className="last-updated">Sample overview · October 2, 2026</p></aside><Records open={open}/></div></main> : <AlternateLayouts layout={layout} open={open} uploaded={uploaded} read={read} file={file} travelSubmitted={travelSubmitted}/>} 
 <footer><div><span className="footer-brand">VA.gov</span><p>Serving those who served.</p><button onClick={()=>open('Help and support')}>Help and support</button><span className="footer-note">Design prototype · Sample data only</span></div></footer>
 <dialog ref={dialog} onClick={e=>{if(e.target===e.currentTarget) dialog.current?.close()}}><div className="dialog-header"><div><p className="eyebrow">MY VA · DEMO</p><h2>{panel}</h2></div><button className="close" aria-label="Close dialog" onClick={()=>dialog.current?.close()}><X/></button></div><div className="dialog-body">
 {['Medical records','Lab results','Service records'].includes(panel) ? <><p>{panel==='Medical records'?'Review your sample visit notes and care summaries.':panel==='Lab results'?'View sample laboratory reports. These fictional values are for interface demonstration only.':'Review sample military service documents. A live version would explain which records are available and how to request missing documents.'}</p>{(panel==='Medical records'?[{title:'Primary care visit note',date:'September 25, 2026',detail:'Denver VA Medical Center · Routine follow-up',content:'Sample visit summary: medication list reviewed and follow-up appointment scheduled. This is fictional content, not a clinical record.'},{title:'After-visit summary',date:'September 25, 2026',detail:'Visit instructions and follow-up',content:'Sample follow-up appointment: October 14, 2026 at 10:30 a.m. Bring your current medication list.'}]:panel==='Lab results'?[{title:'Complete blood count',date:'September 25, 2026',detail:'Sample laboratory report',content:'Illustrative results only: White blood cells 6.5 K/uL; Hemoglobin 14.2 g/dL; Platelets 250 K/uL. Reference ranges and clinical interpretation are not provided in this demo.'},{title:'Basic metabolic panel',date:'September 25, 2026',detail:'Sample laboratory report',content:'Illustrative results only: Sodium 140 mmol/L; Potassium 4.2 mmol/L; Glucose 92 mg/dL. Reference ranges and clinical interpretation are not provided in this demo.'}]:[{title:'DD214 — Certificate of release or discharge',date:'2014',detail:'U.S. Marine Corps · Sample document',content:'FICTIONAL SERVICE RECORD — NOT VALID FOR BENEFIT VERIFICATION. Alex Morgan. U.S. Marine Corps. Service period: 2010–2014. This is a prototype placeholder, not an official DD214.'},{title:'Military service summary',date:'2010–2014',detail:'Service history · Sample document',content:'Fictional veteran: Alex Morgan. Branch: U.S. Marine Corps. Service period: 2010–2014. This sample contains no official personnel information.'}]).map(record=><article className="record-detail" key={record.title}><p className="eyebrow">{record.date}</p><h3>{record.title}</h3><p>{record.detail}</p><details><summary>View details</summary><p>{record.content}</p></details><a className="receipt-link" download={'sample-'+record.title.toLowerCase().replace(/[^a-z0-9]+/g,'-')+'.txt'} href={'data:text/plain;charset=utf-8,'+encodeURIComponent('DESIGN PROTOTYPE — FICTIONAL SAMPLE DATA\n\n'+record.title+'\n'+record.date+'\n\n'+record.content)}>Download sample record</a></article>)}<p className="demo-note">All records are fictional. Downloads are sample text files, not official documents.</p></> :
 panel === 'Document receipts' ? <><p>Receipts confirm arrival, not completion of VA’s review.</p>{[{name:'Supporting statement.pdf',date:'September 28, 2026 · 9:42 a.m.',status:'Received · Awaiting review'},{name:'Medical records.pdf',date:'September 24, 2026 · 2:15 p.m.',status:'Received · Added to claim'},...(uploaded?[{name:file,date:'This demo session',status:'Received · Awaiting review'}]:[])].map(d=><article className="document-receipt" key={d.name}><h3>{d.name}</h3><p>{d.date}</p><span className="status">{d.status}</span></article>)}<p className="demo-note">These are fictional receipts, not confirmations from VA.</p></> :
 panel === 'Prescription tracking' ? <><span className="status">Shipped</span><h3>Sample prescription refill</h3><ol className="timeline"><li><strong>September 28 — Request received</strong></li><li><strong>September 29 — Pharmacy processing</strong></li><li><strong>October 1 — Shipped</strong><p>Estimated delivery October 5–7.</p></li></ol><p>Carrier tracking is unavailable in this demo.</p><button className="secondary" onClick={()=>open('Pharmacy help')}>Contact your pharmacy</button></> :
 panel === 'Pharmacy help' ? <><h3>Get help with your prescription</h3><p>Contact your care team about a delayed refill or a prescription that doesn’t appear in your list.</p><button className="primary" onClick={()=>open('Your messages')}>Open secure messages</button><p className="demo-note">No pharmacy call or message is sent from this prototype.</p></> :
 panel === 'Travel reimbursement' ? <><span className="status">{travelSubmitted?'Submitted in demo':'Not started'}</span><h3>Primary care · September 25, 2026</h3><p>VA Medical Center — Denver, CO</p>{travelSubmitted?<><p className="success"><CheckCircle2 size={20}/>Sample travel claim received.</p><p>Demo receipt: TRAVEL-2026-0925. Status: awaiting review.</p></>:<><p>Before filing, confirm your eligibility, appointment details, travel expenses, and reimbursement information.</p><p className="demo-note">This preview does not determine eligibility or calculate payment. The button below only demonstrates the submitted state.</p><button className="primary" onClick={()=>setTravelSubmitted(true)}>Simulate travel claim submission</button></>}<button className="receipt-link" onClick={()=>open('Missing appointment')}>Can’t find a visit?</button></> :
 panel === 'Missing appointment' ? <><h3>Find help with a missing visit</h3><p>A community care visit or a recently completed appointment may not appear in your list. A live version would connect you to the appropriate travel office or appointment support.</p><button className="secondary" onClick={()=>open('Help and support')}>View support options</button><p className="demo-note">No appointment has been created or changed.</p></> :
 panel === 'Upload a document' ? <><p>Add a sample supporting document to your disability claim. Files stay on your device; this prototype records only the filename for this session.</p><label className="upload"><Upload/><strong>Choose a sample document</strong><span>PDF, JPG, or PNG</span><input type="file" accept=".pdf,.jpg,.jpeg,.png" onChange={e=>setFile(e.target.files?.[0]?.name || '')}/></label>{file && <p className="selected-file">Selected: {file}</p>}<button className="primary" disabled={!file} onClick={()=>{setUploaded(true);dialog.current?.close()}}>Add to demo claim</button></> :
 panel === 'Claim details' || panel === 'Track claims' ? <><span className="status">Step {claim.step} of {claim.totalSteps} — {claim.status}</span><p className="jurisdiction">Temporary jurisdiction: <strong>{claim.temporaryJurisdiction}</strong></p><h3>{claim.title}</h3><p><strong>Last changed: September 29, 2026</strong></p><p>VA is reviewing the records supporting your claim. This stage does not provide a confirmed decision date.</p><button className="receipt-link" onClick={()=>open('Document receipts')}>View document receipts</button><p>Received {claim.received} · {claim.number}</p><ol className="timeline"><li>Claim received</li><li>Initial review completed</li><li><strong>Evidence gathering</strong><p>We’re reviewing the information that supports your claim.</p></li><li className="muted">Evidence review</li><li className="muted">Rating</li><li className="muted">Preparing decision letter</li><li className="muted">Final review</li><li className="muted">Claim decided</li></ol>{uploaded ? <p className="success"><CheckCircle2 size={20}/>Sample document added: {file}</p> : <button className="primary" onClick={()=>open('Upload a document')}>Upload a document</button>}</> :
 panel.includes('appointment') ? <><span className="status">Confirmed</span><h3>{appointment.type}</h3><p>{appointment.date} at {appointment.time}</p><p>{appointment.location}</p><hr/><h3>Before your visit</h3><p>Bring your medication list and arrive 15 minutes early.</p><p className="demo-note">Scheduling changes are not connected in this homepage prototype.</p></> :
 panel === 'Your messages' ? messages.map(m=><article className="message" key={m.subject}><p className="eyebrow">{m.from}</p><h3>{m.subject}</h3><p>{m.body}</p></article>) :
 panel === 'Search VA.gov' ? <><p>Results for <strong>“{query || 'all services'}”</strong></p><div className="result-list">{services.filter(s=>s.toLowerCase().includes(query.toLowerCase())).map(s=><button key={s} onClick={()=>open(s)}>{s}<ChevronRight size={18}/></button>)}{!services.some(s=>s.toLowerCase().includes(query.toLowerCase())) && <p>No matching services. Try “claims”, “letters”, “appointments”, or “prescriptions”.</p>}</div></> :
 panel === 'Your profile' ? <><div className="profile"><span className="avatar">AM</span><div><h3>{veteran.name}</h3><p>{veteran.service}</p><p>{veteran.serviceYears}</p></div></div><hr/><p>This fictional profile is used throughout the homepage preview.</p><p className="demo-note">Profile editing will be part of a future screen.</p></> :
 panel === 'Your benefits' || panel === 'Payment history' ? <><h3>Disability compensation</h3><div className="detail-line"><span>Combined disability rating</span><strong>70%</strong></div><div className="detail-line"><span>October 1, 2026</span><strong>{veteran.lastPayment}</strong></div><div className="detail-line"><span>September 1, 2026</span><strong>{veteran.lastPayment}</strong></div><p className="demo-note">Illustrative amounts for this fictional profile.</p></> :
 panel === 'Refill prescriptions' ? <><h3>Your prescriptions</h3><p>No prescriptions are due for refill in this sample profile.</p><p className="demo-note">Prescription management will be part of a future screen.</p></> :
 panel === 'View VA letters' ? <><h3>Benefit summary letter</h3><p>Your sample benefit summary is available.</p><a className="primary download" download="sample-va-benefit-summary.txt" href={'data:text/plain;charset=utf-8,'+encodeURIComponent('DESIGN PROTOTYPE — NOT AN OFFICIAL VA LETTER\n\nAlex Morgan (fictional profile)\nCombined disability rating: 70%\nThis document contains illustrative sample data only.')}>Download sample letter</a></> : <><p>Explore your VA services.</p><div className="result-list">{services.map(s=><button key={s} onClick={()=>open(s)}>{s}<ChevronRight size={18}/></button>)}</div><p className="demo-note">This is a homepage prototype. {panel} is not connected to a live account.</p></>}
 </div><div className="dialog-footer">Fictional sample data. No information is sent to VA.</div></dialog>
 </div>;
}
