'use client';
import { useRef, useState } from 'react';
import { Bell, ChevronRight, FileText, Folder, GraduationCap, HeartPulse, Mail, Search, ShieldCheck, Upload, Users, X } from 'lucide-react';
import AudienceSwitcher from './AudienceSwitcher';
import Champva from './Champva';
import SupportOptions from './SupportOptions';
import SubmissionReceipt from './SubmissionReceipt';
import { createDemoReceipt, validateDemoFile, type DemoReceipt } from '@/lib/demo-receipts';
import { clients, dependent, representative, type Audience } from '@/lib/audiences';

type Props = { audience: Exclude<Audience, 'veteran'>; onAudience: (value: Audience) => void; onSignOut: () => void };
export default function AudienceHome({ audience, onAudience, onSignOut }: Props) {
  const isDependent = audience === 'dependent';
  const person = isDependent ? dependent : representative;
  const [clientId, setClientId] = useState(clients[0].id);
  const client = clients.find(c => c.id === clientId)!;
  const authorized = client.authorization === 'Active';
  const [panel, setPanel] = useState('');
  const [showChampva, setShowChampva] = useState(false);
  const [query, setQuery] = useState('');
  const [read, setRead] = useState(false);
  const [attachments, setAttachments] = useState<Record<string, DemoReceipt>>({});
  const [insuranceUpdated, setInsuranceUpdated] = useState(false);
  const [schoolSent, setSchoolSent] = useState(false);
  const [file, setFile] = useState('');
  const [uploadError, setUploadError] = useState('');
  const [certificationReceipt, setCertificationReceipt] = useState<DemoReceipt | null>(null);
  const [reviewedRequests, setReviewedRequests] = useState<Record<string, boolean>>({});
  const dialog = useRef<HTMLDialogElement>(null);
  const attachmentKey = isDependent ? 'dependent' : client.id;
  const receipt = attachments[attachmentKey];
  const attached = receipt?.filename;
  const actions = isDependent
    ? ['CHAMPVA coverage', 'Health claim details', 'Member ID card', 'Other health insurance', 'Education application', 'School certification', 'Benefit letters']
    : ['Client roster', 'Representation status', ...(authorized ? ['Client claim details', 'Upload client evidence', 'Client documents', 'Client follow-up'] : []), 'Representative resources'];
  const messages = isDependent
    ? [{ from: 'CHAMPVA claims team', subject: 'Explanation of benefits requested', body: 'Please attach the explanation of benefits for your September 28 office visit. This request concerns Sofia’s own sample claim.' }, { from: 'Education benefits team', subject: 'School information needed', body: 'Add your school and program to continue your sample education application. A decision has not been made.' }]
    : [{ from: 'Claims work queue', subject: 'James Wilson: evidence requested', body: 'A supporting statement is requested for DEMO-201. Review the request in James’s authorized case.' }, { from: 'Representation team', subject: 'Sam Taylor: appointment pending', body: 'The sample appointment of representative is pending. Claim documents are unavailable until authorization is active.' }];
  function open(title: string) { if (isDependent && title === 'CHAMPVA coverage') { dialog.current?.close(); setShowChampva(true); window.scrollTo(0,0); return; } setPanel(title); setFile(''); setUploadError(''); if (title === 'Your messages') setRead(true); dialog.current?.showModal(); }
  const quick = <div className="alternate-quick">{actions.map(label => <button key={label} onClick={() => open(label)}><FileText size={25}/><span>{label}</span><ChevronRight size={17}/></button>)}</div>;
  const tile = (label: string, title: string, detail: string, target: string) => <button onClick={() => open(target)}><FileText/><span><small>{label}</small><strong>{title}</strong><span>{detail}</span></span><ChevronRight/></button>;
  const download = (title: string, body: string) => <a className="primary download" download={`sample-${audience}-${title.toLowerCase().replace(/[^a-z0-9]+/g, '-')}.txt`} href={'data:text/plain;charset=utf-8,' + encodeURIComponent(`DESIGN PROTOTYPE — FICTIONAL SAMPLE DATA\n\n${title}\n${body}`)}>Download sample document</a>;
  if (isDependent && showChampva) return <Champva layout={3} audience="dependent" onAudience={onAudience} initialDocument={attached} onDocument={filename => setAttachments(previous => ({ ...previous, dependent: createDemoReceipt(filename) }))} onBack={() => { setShowChampva(false); window.scrollTo(0,0); }}/>;
  return <div className="layout-version layout-version-3">
    <a className="skip-link" href="#main">Skip to main content</a>
    <header className="header"><div className="header-inner audience-header"><a className="brand" href="#" onClick={e => { e.preventDefault(); onSignOut(); }}><strong>VA</strong><span>U.S. Department of<br/>Veterans Affairs</span></a><nav className="audience-navigation" aria-label="Main navigation"><button onClick={onSignOut}>VA.gov home</button>{(isDependent ? ['CHAMPVA coverage', 'Education application', 'School certification', 'Benefit letters'] : ['Client roster', 'Representation status', 'Representative resources']).map(label => <button key={label} onClick={() => open(label)}>{label}</button>)}</nav><div className="header-tools"><form className="search" role="search" onSubmit={e => { e.preventDefault(); open('Search services'); }}><button aria-label="Search services"><Search size={19}/></button><input aria-label="Search services" placeholder="Search services" value={query} onChange={e => setQuery(e.target.value)}/></form><button className="notification" aria-label={read ? 'No unread messages' : '2 unread messages'} onClick={() => open('Your messages')}><Bell size={23}/>{!read && <span/>}</button><button className="account" onClick={() => open('Your profile')}><span className="avatar small">{person.initials}</span>{person.firstName}</button></div></div></header>
    <div className="prototype"><AudienceSwitcher audience={audience} onChange={onAudience}/><button className="demo-signout" onClick={onSignOut}>Return to public homepage</button><span className="prototype-note">Design preview · Fictional sample data · Not an official VA website</span></div>
    <div className="crisis-bar"><div><a href="https://www.veteranscrisisline.net/" target="_blank" rel="noreferrer">Veterans Crisis Line: 988 then press 1</a></div></div>
    <div className="alternate-shell alternate-3"><main id="main" className="alternate-main">
      <div className="welcome-profile-row"><header className="alternate-welcome"><p className="eyebrow">MY VA · {isDependent ? 'DEPENDENT' : 'REPRESENTATIVE'}</p><h1>Welcome back, {person.firstName}</h1><p>{isDependent ? 'Your coverage, education benefits, and next steps, in one place.' : 'Stay on top of your clients’ claims and requested evidence.'}</p></header><section className="shared-profile-card" aria-label={`${person.name} profile`}><div className="shared-profile-banner audience-profile-banner"><ShieldCheck size={35}/><span>MY VA<br/><strong>{isDependent ? 'DEPENDENT' : 'REPRESENTATIVE'}</strong></span></div><div className="shared-profile-body"><span className="shared-profile-avatar">{person.initials}</span><div><h2>{person.name}</h2><p>{person.description}</p><p>{isDependent ? 'Independent sample dependent account' : '2 authorized clients · 1 pending appointment'}</p></div></div></section></div>
      {!isDependent && <section className="client-context"><label htmlFor="client-select">Working on behalf of</label><select id="client-select" value={clientId} onChange={e => { setClientId(e.target.value); setFile(''); }} >{clients.map(c => <option key={c.id} value={c.id}>{c.name} · {c.authorization === 'Active' ? 'Authorized' : 'Authorization pending'}</option>)}</select><span className="status">{client.authorization === 'Active' ? 'Authorized claims access' : 'Awaiting authorization'}</span></section>}
      <section className="updates-surface" aria-label="Recent updates and next steps"><div className="updates-heading"><div><p className="eyebrow">YOUR NEXT STEPS</p><h2>Needs your attention</h2></div><span>October 2, 2026 · Sample data</span></div><div className="updates-grid">
        {isDependent ? <><article><HeartPulse size={24}/><p className="eyebrow">YOUR HEALTH CLAIM</p><h3>{attached ? 'Document received' : 'An explanation of benefits is needed'}</h3><p>Office visit · September 28 · DEMO-DEP-1001</p><div className="update-callout"><strong>{attached ? 'Awaiting review' : 'Your next step'}</strong><p>{attached || 'Attach the requested document for your own CHAMPVA claim.'}</p></div><button className="primary" onClick={() => open(attached ? 'Health claim details' : 'Upload health document')}>{attached ? 'View claim' : 'Upload document'}</button></article><article><GraduationCap size={24}/><p className="eyebrow">YOUR EDUCATION</p><h3>{schoolSent ? 'School information received' : 'Complete your school information'}</h3><p>Your sample education application is awaiting review.</p><button className="text-link" onClick={() => open('Education application')}>Review application<ChevronRight size={17}/></button></article><article><ShieldCheck size={24}/><p className="eyebrow">YOUR COVERAGE</p><h3>{insuranceUpdated ? 'Insurance update received' : 'Review your other health insurance'}</h3><p>Keep your sample insurance information current for claim review.</p><button className="text-link" onClick={() => open('Other health insurance')}>Review insurance<ChevronRight size={17}/></button></article></>
        : <><article><Upload size={24}/><p className="eyebrow">{client.name.toUpperCase()} · EVIDENCE</p><h3>{!authorized ? 'Authorization is pending' : attached ? 'Evidence received' : client.request || 'No outstanding requests'}</h3><p>{!authorized ? 'Case information is available after the sample appointment is active.' : attached ? `${attached} · Awaiting review` : client.request ? `Sample response date: ${client.due}` : 'This claim is in evidence review.'}</p><button className="primary" onClick={() => open(!authorized ? 'Representation status' : client.request && !attached ? 'Upload client evidence' : 'Client claim details')}>{!authorized ? 'Review authorization' : client.request && !attached ? 'Upload evidence' : 'View claim'}</button></article><article><Users size={24}/><p className="eyebrow">YOUR CLIENTS</p><h3>2 authorized clients</h3><p>Review active appointments and the pending request for Sam Taylor.</p><button className="text-link" onClick={() => open('Client roster')}>View client roster<ChevronRight size={17}/></button></article><article><ShieldCheck size={24}/><p className="eyebrow">REPRESENTATION</p><h3>1 appointment pending</h3><p>Sam Taylor · Appointment of representative received in this demo.</p><button className="text-link" onClick={() => open('Representation status')}>Review appointments<ChevronRight size={17}/></button></article></>}
      </div></section>
      <div className="personal-grid"><section className="at-a-glance"><h2>{isDependent ? 'Your benefits at a glance' : `${client.name}’s case at a glance`}</h2>{isDependent ? <>{tile('HEALTH COVERAGE', 'CHAMPVA · Current term active in demo', 'Open your CHAMPVA dashboard for coverage, claims, and your member card.', 'CHAMPVA coverage')}{tile('SCHOOL CERTIFICATION', certificationReceipt ? 'Received · Awaiting review' : 'Next-term certification needed', 'Current sample term ends December 18, 2026.', 'School certification')}{tile('EDUCATION APPLICATION', schoolSent ? 'School details received' : dependent.educationStatus, 'Sample application · No eligibility decision made', 'Education application')}{tile('HEALTH CLAIM', attached ? 'In review' : 'Action needed', 'Office visit · September 28, 2026', 'Health claim details')}</> : authorized ? <>{tile('CLAIM', client.claim, `${client.id} · ${client.status}`, 'Client claim details')}{tile('EVIDENCE', attached ? 'Document received' : client.request || 'No action needed', attached || (client.due ? `Sample response date: ${client.due}` : 'No outstanding document requests'), 'Client documents')}{tile('REPRESENTATION', 'Active appointment', `Claims assistance for ${client.name}`, 'Representation status')}</> : <p className="audience-empty">Sam’s claim information and documents are unavailable while authorization is pending.</p>}</section><div className="personal-updates"><section className="alternate-card"><Mail size={26}/><p className="eyebrow">YOUR MESSAGES</p><h2>{read ? 'You’re all caught up' : '2 unread messages'}</h2><p>{isDependent ? 'Updates about your health claim and education application.' : 'Updates from the claims and representation teams.'}</p><button className="text-link" onClick={() => open('Your messages')}>View messages</button></section><section className="alternate-card"><ShieldCheck size={26}/><p className="eyebrow">{isDependent ? 'SCHOOL AND COVERAGE' : 'CLIENT FOLLOW-UP'}</p><h2>{isDependent ? certificationReceipt ? 'Certification received' : 'Track your next school term' : reviewedRequests[client.id] ? 'Request reviewed in demo' : authorized ? 'Keep your client in the loop' : 'Appointment still pending'}</h2><p>{isDependent ? 'School certification for CHAMPVA is tracked separately from your education-benefit application.' : 'See the request, who was notified in the demo, and the next follow-up.'}</p><button className="text-link" onClick={() => open(isDependent ? 'School certification' : authorized ? 'Client follow-up' : 'Representation status')}>{isDependent ? 'View school certification' : 'Review follow-up'}</button></section></div></div>
      <section className="personal-services"><h2>What would you like to do?</h2>{quick}</section>
      <section className="records-section"><div className="records-heading"><h2>{isDependent ? 'Your documents' : 'Client documents'}</h2><p>{isDependent ? 'Your own coverage, education, and claim correspondence.' : `Claims documents for ${client.name} within the sample authorization.`}</p></div>{!isDependent && !authorized ? <p className="audience-empty">Documents will appear after authorization is active.</p> : <div className="records-grid">{(isDependent ? [{ title: 'Coverage letter', detail: 'Your sample CHAMPVA coverage summary', panel: 'Benefit letters' }, { title: 'Education application', detail: 'Application and school information', panel: 'Education application' }, { title: 'Health claim receipts', detail: 'Documents received for your own claim', panel: 'Health claim details' }] : [{ title: 'Claim correspondence', detail: `${client.name} · Request and status summary`, panel: 'Client documents' }, { title: 'Evidence receipts', detail: attached || 'Review sample evidence received', panel: 'Client documents' }, { title: 'Appointment of representative', detail: 'Active sample authorization', panel: 'Representation status' }]).map(record => <button key={record.title} onClick={() => open(record.panel)}><Folder size={24}/><h3>{record.title}</h3><p>{record.detail}</p><strong>View document<ChevronRight size={16}/></strong></button>)}</div>}</section>
      <section className="alternate-benefits"><h2>{isDependent ? 'Your account and coverage' : 'Your representative workspace'}</h2><div><button onClick={() => open('Your profile')}><span>Your profile</span><strong>{person.name}</strong><small>{person.description}</small></button><button onClick={() => open(isDependent ? 'Member ID card' : 'Client roster')}><span>{isDependent ? 'Member information' : 'Client roster'}</span><strong>{isDependent ? dependent.memberId : '2 active · 1 pending'}</strong><small>{isDependent ? 'View your sample member card' : 'Review representation status'}</small></button><button onClick={() => open(isDependent ? 'Education application' : 'Representative resources')}><span>{isDependent ? 'Education' : 'Resources'}</span><strong>{isDependent ? 'Application in progress' : 'Claims assistance'}</strong><small>{isDependent ? 'Review your next step' : 'Accreditation and representation resources'}</small></button></div></section>
      <SupportOptions audience={audience}/>
    </main></div>
    <footer><div><span className="footer-brand">VA.gov</span><p>Serving those who served.</p><button onClick={() => open('Help and support')}>Help and support</button><span className="footer-note">Design prototype · Sample data only</span></div></footer>
    <dialog ref={dialog} aria-labelledby="audience-dialog-title" onClick={e => { if (e.target === e.currentTarget) dialog.current?.close(); }}><div className="dialog-header"><div><p className="eyebrow">MY VA · {isDependent ? 'DEPENDENT' : 'REPRESENTATIVE'} DEMO</p><h2 id="audience-dialog-title">{panel}</h2></div><button className="close" aria-label="Close dialog" onClick={() => dialog.current?.close()}><X/></button></div><div className="dialog-body">
      {panel === 'Help and support' ? <SupportOptions audience={audience}/>
      : panel === 'Your messages' ? messages.map(m => <article className="message" key={m.subject}><p className="eyebrow">{m.from}</p><h3>{m.subject}</h3><p>{m.body}</p></article>)
      : panel === 'Your profile' ? <><h3>{person.name}</h3><p>{person.description}</p><p>{isDependent ? `Sponsor: ${dependent.sponsor} · Separate fictional household. This view contains Sofia’s own benefit information.` : 'Sample accreditation profile. Client access depends on an active appointment in this demo.'}</p></>
      : panel === 'Search services' ? <div className="result-list">{actions.filter(a => a.toLowerCase().includes(query.toLowerCase())).map(a => <button key={a} onClick={() => open(a)}>{a}<ChevronRight size={18}/></button>)}{!actions.some(a => a.toLowerCase().includes(query.toLowerCase())) && <p>No matching services. Try {isDependent ? 'coverage or education' : 'client or representation'}.</p>}</div>
      : ['Upload health document', 'Upload client evidence', 'Upload school certification'].includes(panel) ? (!isDependent && !authorized ? <p>An active appointment is needed to attach client evidence.</p> : <form onSubmit={e => { e.preventDefault(); if (!file || uploadError) return; const nextReceipt = createDemoReceipt(file); if (panel === 'Upload school certification') { setCertificationReceipt(nextReceipt); setPanel('School certification'); } else { setAttachments(previous => ({ ...previous, [attachmentKey]: nextReceipt })); setPanel(isDependent ? 'Health claim details' : 'Client claim details'); } }}><p>{panel === 'Upload school certification' ? 'Add a sample school-official certification for Sofia’s next term. This records receipt only; it does not extend coverage.' : isDependent ? 'Attach the requested explanation of benefits (your other insurer’s claim summary) for Sofia Chen’s office visit.' : `Attach the requested supporting statement to ${client.name}’s ${client.claim.toLowerCase()} (${client.id}).`}</p><div className="case-explanation"><strong>Before you add a document</strong><p>Check the person, reference, and requested document. PDF, JPG, and PNG are supported in this demo. Save the receipt afterward so you can track what was recorded.</p></div><label className="upload"><Upload/><strong>Choose a sample document</strong><input type="file" required accept=".pdf,.jpg,.jpeg,.png" aria-describedby="audience-upload-error" onChange={e => { const chosen = e.target.files?.[0]; const existing = panel === 'Upload school certification' ? certificationReceipt : receipt; const error = validateDemoFile(chosen) || (chosen && existing?.filename === chosen.name ? 'A document with this filename already has a demo receipt. Review the receipt before adding it again.' : ''); setUploadError(error); setFile(error ? '' : chosen?.name || ''); }}/></label>{file && <p>Selected: {file}</p>}<p id="audience-upload-error" className="audience-file-error" role={uploadError ? 'alert' : undefined}>{uploadError}</p><p className="demo-note">Only the filename is saved in this session. Files stay on your device.</p><button className="primary" disabled={!file || !!uploadError}>Add sample document</button></form>)
      : panel === 'School certification' ? <><h3>{dependent.name} · School certification for CHAMPVA</h3><span className="status">{certificationReceipt ? 'Received · Awaiting review' : 'Next term · Document needed'}</span><p>Reference: DEMO-SCHOOL-401 · Current sample term: August 24–December 18, 2026.</p><div className="case-explanation"><strong>What this means for your coverage</strong><p>Your current term is active in this demo. The next sample term (January 11–May 14, 2027) {certificationReceipt ? 'is awaiting certification review' : 'needs a school certification'}. Recording a document does not confirm review or extend coverage.</p><p>This tracker is separate from the education-benefit application. Ask your school for the certification information and check the official CHAMPVA instructions.</p></div>{certificationReceipt ? <SubmissionReceipt receipt={certificationReceipt} context="Sofia Chen · DEMO-SCHOOL-401 · Next-term school certification"/> : <button className="primary" onClick={() => open('Upload school certification')}>Add sample school certification</button>}<p><a href="https://www.va.gov/COMMUNITYCARE/docs/pubfiles/forms/CHAMPVA-School-Enrollment.pdf" target="_blank" rel="noreferrer">Official CHAMPVA school enrollment certification instructions (PDF)</a></p><SupportOptions audience="dependent"/></>
      : panel === 'Client follow-up' ? (!authorized ? <p>Claims follow-up is unavailable while the appointment is pending.</p> : <><p className="eyebrow">WORKING ON BEHALF OF {client.name.toUpperCase()}</p><h3>Request and communication history</h3><p>{client.id} · {client.claim}</p><ol className="timeline"><li><strong>October 1 · {client.request ? 'Evidence requested' : 'Status update'}</strong><p>{client.request || 'No outstanding evidence request.'}</p></li><li><strong>Client and representative notified in demo</strong><p>The same sample request is visible to {client.name} and Dana Brooks. No email or text was sent.</p></li>{receipt && <li><strong>Evidence recorded in demo</strong><p>{receipt.filename} · Receipt {receipt.id} · Awaiting review</p></li>}<li><strong>{reviewedRequests[client.id] ? 'Reviewed by representative in demo' : 'Representative review pending'}</strong><p>{client.request && !receipt ? `Next step: ${reviewedRequests[client.id] ? 'prepare the requested supporting statement with your client' : 'review the request with your client'}. Sample response date: ${client.due}.` : 'Next step: monitor the claim status and any new requests.'}</p></li></ol>{!reviewedRequests[client.id] && <button className="primary" onClick={() => setReviewedRequests(previous => ({ ...previous, [client.id]: true }))}>Mark request reviewed in demo</button>}<p className="demo-note">This records your review only. It does not contact your client or submit a response to VA.</p></>)
      : panel === 'CHAMPVA coverage' ? <><span className="status">Active · Sample coverage</span><h3>{dependent.name}</h3><p>Member ID: {dependent.memberId}</p><p>Your current sample school term is active through December 18, 2026. Next-term certification is tracked separately. This is fictional coverage; the prototype does not determine eligibility.</p><button className="primary" onClick={() => open('Member ID card')}>View member ID card</button><button className="receipt-link" onClick={() => open('School certification')}>Track school certification</button><p><a href="https://www.va.gov/family-and-caregiver-benefits/health-and-disability/champva/" target="_blank" rel="noreferrer">CHAMPVA information on VA.gov</a></p></>
      : panel === 'Member ID card' ? <><div className="audience-member-card"><ShieldCheck/><h3>CHAMPVA</h3><p>{dependent.name}</p><strong>{dependent.memberId}</strong><p>SAMPLE — NOT VALID</p></div>{download('Member card', `${dependent.name}\n${dependent.memberId}\nSAMPLE — NOT VALID FOR CARE`)}</>
      : panel === 'Health claim details' ? <><h3>Sofia Chen · Office visit</h3><span className="status">{attached ? 'In review' : 'Action needed'}</span><p>DEMO-DEP-1001 · September 28, 2026 · Sample amount submitted: $125.00</p><p>{attached ? `Document received: ${attached}. Awaiting review.` : 'An explanation of benefits is requested for this sample claim.'}</p>{!attached && <button className="primary" onClick={() => open('Upload health document')}>Upload requested document</button>}{receipt && <SubmissionReceipt receipt={receipt} context="Sofia Chen · DEMO-DEP-1001 · Explanation of benefits"/>}<div className="case-explanation"><strong>What is needed?</strong><p>The sample request is for your other insurer’s explanation of benefits. Receipt is recorded separately from claim review; a payment decision has not been made.</p><p>Last status update: October 2, 2026. Waiting on: {attached ? 'claim review' : 'your requested document'}. No completion date is available in this demo.</p></div><SupportOptions audience="dependent"/></>
      : panel === 'Other health insurance' ? <><h3>Your other health insurance</h3><p>Sample insurer: Example Health Plan · Last reviewed September 20, 2026.</p>{insuranceUpdated ? <p className="success">Sample insurance update received.</p> : <form onSubmit={e => { e.preventDefault(); setInsuranceUpdated(true); }}><label className="audience-field">Insurance company<input required maxLength={80} placeholder="Use a fictional company"/></label><label className="audience-field">Policy reference<input required maxLength={40} placeholder="Use a sample reference"/></label><button className="primary">Save sample insurance update</button></form>}</>
      : panel === 'Education application' ? <><h3>{dependent.name} · Education application</h3><span className="status">{schoolSent ? 'School information received' : 'Awaiting school information'}</span><p>DEMO-EDU-301 · This sample application has no eligibility decision or payment award.</p>{schoolSent ? <p>Your sample school information is awaiting review.</p> : <form onSubmit={e => { e.preventDefault(); setSchoolSent(true); }}><label className="audience-field">School<input required maxLength={100} placeholder="Fictional school name"/></label><label className="audience-field">Program<input required maxLength={100} placeholder="Sample course or program"/></label><button className="primary">Send sample school information</button></form>}<p><a href="https://www.va.gov/family-and-caregiver-benefits/education-and-careers/" target="_blank" rel="noreferrer">Education benefits for family members</a></p></>
      : panel === 'Benefit letters' ? <><h3>Your sample coverage summary</h3><p>A letter for Sofia’s own coverage. This does not contain the sponsor’s disability or service records.</p>{download('Coverage summary', `${dependent.name}\n${dependent.memberId}\nCHAMPVA coverage: active in fictional demo\nNot an official coverage or eligibility determination`)}</>
      : panel === 'Client roster' ? <div className="result-list">{clients.map(c => <button key={c.id} onClick={() => { setClientId(c.id); setPanel(c.authorization === 'Active' ? 'Client claim details' : 'Representation status'); }}><span>{c.name} · {c.authorization}<span className="roster-detail">{c.authorization === 'Active' ? `${c.id} · ${c.status} · ${attachments[c.id] ? 'Evidence received' : c.request ? 'Document requested · Sample response date: ' + c.due : 'No outstanding request'}` : 'Appointment pending · Case information unavailable'}</span></span><ChevronRight size={18}/></button>)}</div>
      : panel === 'Representation status' ? <>{clients.map(c => <article className="message" key={c.id}><h3>{c.name}</h3><span className="status">{c.authorization} appointment</span><p>{c.authorization === 'Active' ? 'Sample authorization covers claims assistance and related correspondence.' : 'Appointment received in demo. Claims access has not been enabled.'}</p></article>)}</>
      : panel === 'Client claim details' || panel === 'Client documents' ? (!authorized ? <p>Client information is unavailable while authorization is pending.</p> : <><p className="eyebrow">WORKING ON BEHALF OF {client.name.toUpperCase()}</p><h3>{client.claim}</h3><span className="status">{client.status}</span><p>Claim: {client.id}</p><div className="case-explanation"><strong>What this status means</strong><p>{client.status === 'Evidence gathering' ? 'Supporting records are being collected. The outstanding request is shown below.' : 'The available evidence is being reviewed. No document is currently requested in this sample case.'}</p><p>Last status update: October 2, 2026. Waiting on: {client.request && !receipt ? 'requested supporting statement' : 'claim review'}. No confirmed decision date is available in this demo.</p></div><p>{attached ? `Evidence received: ${attached}. Awaiting review.` : client.request ? `Requested: ${client.request}. Sample response date: ${client.due}.` : 'No outstanding evidence requests in this sample case.'}</p>{!attached && client.request && <button className="primary" onClick={() => open('Upload client evidence')}>Upload requested evidence</button>}<button className="receipt-link" onClick={() => open('Client follow-up')}>View request and communication history</button>{receipt && <SubmissionReceipt receipt={receipt} context={`${client.name} · ${client.id} · Claim evidence`}/>}<article className="record-detail"><h3>{panel === 'Client documents' ? 'Claim correspondence and evidence receipt' : 'Sample claim summary'}</h3>{download(`Claim summary ${client.id}`, `${client.name}\n${client.claim}\n${client.status}\n${attached ? 'Evidence received: ' + attached : client.request || 'No outstanding evidence requests'}`)}</article></>)
      : <><p>{isDependent ? 'Find information about your own dependent benefits and coverage.' : 'Find resources for accredited claims representatives and client appointments.'}</p><div className="result-list">{actions.map(a => <button key={a} onClick={() => open(a)}>{a}<ChevronRight size={18}/></button>)}</div><p><a href={isDependent ? 'https://www.va.gov/family-and-caregiver-benefits/' : 'https://www.va.gov/ogc/accreditation.asp'} target="_blank" rel="noreferrer">{isDependent ? 'Family and dependent benefits on VA.gov' : 'Accreditation and representation resources on VA.gov'}</a></p></>}
    </div><div className="dialog-footer">Fictional sample data. No information is sent to VA.</div></dialog>
  </div>;
}
