import { GraduationCap, BookOpen, FileText, CalendarCheck, ExternalLink, ChevronRight, Phone } from 'lucide-react';
import { educationBenefits as education } from '@/lib/mock-data';

export const educationPanels = ['GI Bill benefits', 'Enrollment verification', 'Education payments', 'Education letters'];
const resources = [
 {title:'Compare schools and programs',detail:'Open the GI Bill Comparison Tool to explore approved programs.',url:'https://www.va.gov/education/gi-bill-comparison-tool/'},
 {title:'Find Yellow Ribbon schools',detail:'Explore participating schools and program information.',url:'https://www.va.gov/education/yellow-ribbon-participating-schools/'},
 {title:'Choose a GI Bill-approved school',detail:'Review VA’s guidance before choosing a school or training program.',url:'https://www.va.gov/resources/choosing-a-gi-bill-approved-school/'},
 {title:'Explore VR&E and career support',detail:'Learn about Veteran Readiness and Employment and training support.',url:'https://www.va.gov/careers-employment/vocational-rehabilitation/'},
];

type Props = { open: (title: string) => void; verified: boolean };
export default function EducationBenefits({ open, verified }: Props) {
 return <section className="education-section" aria-labelledby="education-heading" id="education-benefits">
  <div className="education-heading"><div><p className="eyebrow">SCHOOL · TRAINING · YOUR NEXT CHAPTER</p><h2 id="education-heading">Your education benefits</h2><p>Manage your GI Bill, keep enrollment current, and plan your next step.</p></div><GraduationCap size={36}/></div>
  <div className="education-grid">
   <article><BookOpen size={26}/><p className="eyebrow">YOUR GI BILL</p><h3>{education.program}</h3><p className="education-value">{education.remaining}</p><p>Remaining entitlement · Fictional sample</p><button className="text-link" onClick={() => open('GI Bill benefits')}>View benefit details<ChevronRight size={17}/></button></article>
   <article><CalendarCheck size={26}/><p className="eyebrow">YOUR ENROLLMENT</p><h3>{verified ? 'Verification received in demo' : 'Verify September enrollment'}</h3><p>{education.school}<br/>{education.course}</p><span className="status">{verified ? 'Received · Awaiting processing' : 'Action needed · Sample'}</span><button className={verified ? 'text-link' : 'primary'} onClick={() => open('Enrollment verification')}>{verified ? 'View verification receipt' : 'Review enrollment verification'}</button></article>
   <article><FileText size={26}/><p className="eyebrow">PAYMENTS AND LETTERS</p><h3>Keep your school documents handy</h3><p>See education payments and your sample decision letter.</p><button className="text-link" onClick={() => open('Education payments')}>View education payments<ChevronRight size={17}/></button><button className="text-link" onClick={() => open('Education letters')}>View education letters<ChevronRight size={17}/></button></article>
  </div>
  <div className="education-resources"><h3>School and training resources</h3><div>{resources.map(resource => <a key={resource.title} href={resource.url} target="_blank" rel="noreferrer"><span><strong>{resource.title}</strong><span>{resource.detail}</span></span><ExternalLink size={18}/></a>)}</div></div>
  <div className="education-footer"><a href="https://www.va.gov/education/how-to-apply/" target="_blank" rel="noreferrer">Apply for or learn about education benefits<ExternalLink size={15}/></a><a href="tel:8884424551"><Phone size={17}/>GI Bill help: 888-442-4551</a></div>
  <p className="education-note">All account values are fictional. School resources open official VA pages.</p>
 </section>;
}

export function EducationPanel({ panel, open, verified, onVerify, name }: Props & { panel: string; onVerify: () => void; name: string }) {
 const sampleDownload = (title: string, content: string) => <a className="primary download" download={`sample-education-${title}.txt`} href={'data:text/plain;charset=utf-8,' + encodeURIComponent(`FICTIONAL EDUCATION DEMO — NOT AN OFFICIAL VA DOCUMENT\n\n${name}\n${education.reference}\n${content}`)}>Download sample {title === 'decision-letter' ? 'decision letter' : 'verification receipt'}</a>;
 return <><p className="eyebrow">{name} · {education.reference}</p>
  {panel === 'GI Bill benefits' ? <><h3>{education.program}</h3><div className="detail-line"><span>Sample remaining entitlement</span><strong>{education.remaining}</strong></div><p>These months and days are a fictional account balance. They are not a forecast of how many courses or semesters you can take.</p><div className="case-explanation"><strong>Your current sample school term</strong><p>{education.school} · {education.course}<br/>{education.term} · {education.credits}</p><p>School certification: received in demo September 24. Monthly enrollment verification: {verified ? 'received in demo' : 'September verification needed'}. These are separate steps.</p></div><button className="primary" onClick={() => open('Enrollment verification')}>Review enrollment</button><p><a href="https://www.va.gov/education/check-remaining-benefits/" target="_blank" rel="noreferrer">Check your actual remaining benefits on VA.gov</a></p></>
  : panel === 'Enrollment verification' ? <><h3>{education.verificationMonth} enrollment</h3><span className="status">{verified ? 'Received in demo · Awaiting processing' : 'Action needed · Sample'}</span><p>{education.school} · {education.course}</p><div className="detail-line"><span>Dates for this sample month</span><strong>{education.verificationDates}</strong></div><div className="detail-line"><span>Sample enrollment</span><strong>{education.credits}</strong></div>{verified ? <><p className="success">Sample verification recorded: DEMO-VERIFY-2026-09.</p>{sampleDownload('verification-receipt', `DEMO-VERIFY-2026-09\n${education.verificationMonth}\n${education.school}\n${education.credits}\nRecorded in demo; awaiting processing. No verification was sent to VA.`)}</> : <form onSubmit={e => { e.preventDefault(); onVerify(); }}><label className="education-confirm"><input type="checkbox" required/>I’ve reviewed the fictional dates and credit hours shown above.</label><button className="primary">Simulate enrollment verification</button></form>}<p className="demo-note">This demonstration does not verify real enrollment or release a payment.</p><p><a href="https://www.va.gov/education/verify-school-enrollment/" target="_blank" rel="noreferrer">Verify real enrollment or review other verification options on VA.gov</a></p></>
  : panel === 'Education payments' ? <><h3>Your sample education payments</h3><article className="document-receipt"><h3>August housing allowance · Sample</h3><p>{education.lastPayment} · Recorded as sent {education.paymentDate}</p><p>Amount is illustrative and is not based on your location, course load, or actual entitlement.</p></article><article className="document-receipt"><h3>September housing allowance · Sample</h3><span className="status">{verified ? 'Awaiting processing in demo' : 'Awaiting sample enrollment verification'}</span><p>No payment date or amount is confirmed for this sample month.</p><button className="text-link" onClick={() => open('Enrollment verification')}>Review enrollment verification</button></article><p>Education payments are shown separately from disability compensation.</p></>
  : <><h3>Post-9/11 GI Bill decision letter · Sample</h3><p>Purpose: show the sample education decision and remaining entitlement when planning school. This is separate from your disability benefit summary.</p>{sampleDownload('decision-letter', `${education.program}\nRemaining entitlement: ${education.remaining} (fictional)\nIllustrative education decision letter. Not a Certificate of Eligibility and not valid for school enrollment or benefit verification.`)}<p><a href="https://www.va.gov/education/download-letters/" target="_blank" rel="noreferrer">Download or request your actual education letter on VA.gov</a></p></>}
  <p><a href="tel:8884424551">GI Bill questions: 888-442-4551</a></p>
 </>;
}
